# Ejercicios NumPy

#### Importar NumPy como np

In [3]:
import numpy as np

#### Generar un array de 10 ceros

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Generar un array con 10 unos

In [14]:
unos = np.ones(10)
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
unos = unos.astype("int")
unos

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Generar un array con 10 seises

In [16]:
np.ones(10) * 6

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

#### Generar un array de números enteros entre el 20 y el 40 (incluidos ambos)

In [17]:
np.arange(20,41)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

#### Generar un array con todos los números pares desde el 15 al 59

In [18]:
np.arange(16,60,2)

array([16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48,
       50, 52, 54, 56, 58])

#### Generar una matriz de 4x3 cuyos valores estén comprendidos entre el 0 y el 11

In [19]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### Generar una matriz identidad de 4x4

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Generar un número aleatorio entre 0 y 1

In [23]:
np.random.rand(1)

array([0.14651948])

#### Generar un número aleatorio entre 0 y 2

In [24]:
np.random.rand(1) * 2

array([0.00494366])

#### Usar NumPy para generar un array de 25 números aleatorios extraídos de una distribución normal.

In [25]:
np.random.randn(25)

array([-1.03705273, -0.10296264, -0.78625034, -0.69360117,  0.22315223,
        0.28852527, -0.29688682,  0.12479624, -0.40442898, -1.71891295,
        1.84274088, -0.79376527,  1.83259809,  0.72201406, -1.2862649 ,
       -0.60747222, -0.50861884,  0.14655008, -1.54597446,  0.15855726,
        1.60562731,  0.60699483, -1.29223003,  0.11196872, -1.11259729])

#### Generar una matriz de 10x10 cuyos valores estén comprendidos entre 0.01 y 1, en incrementos de 0.01:

In [26]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [27]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Generar un array de 20 elementos comprendidos entre el 0 y 1.

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [28]:
np.random.seed(123)
np.random.rand(20)

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897,
       0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752,
       0.34317802, 0.72904971, 0.43857224, 0.0596779 , 0.39804426,
       0.73799541, 0.18249173, 0.17545176, 0.53155137, 0.53182759])

## Indexación y selección en Numpy

#### Generar un array de 5x5, con valores correlativos entre 1 y 25.  Guardar dicho array en el objeto "mat"

In [29]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Mostrar los datos contenidos en mat, a partir de la fila 3 y la columna 2 (tened en cuenta que existen la fila 0 y la columna 0).

In [30]:
mat [2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### Extraer el valor de la celda que situado entre la cuarta fila y la quinta columna

In [31]:
mat[3,4]

20

#### Extraer los valores comprendidos en las 2 primeras filas y las columnas 2 y 3

In [32]:
mat[:2,1:3]

array([[2, 3],
       [7, 8]])

#### Extraer los elementos de la quinta fila

In [ ]:
mat[-1]

array([21, 22, 23, 24, 25])

In [33]:
mat[-1,:]
mat[-1][:]
mat[4,:]

array([21, 22, 23, 24, 25])

In [34]:
mat[4]

array([21, 22, 23, 24, 25])

#### Extraer los elementos de las filas 4 y 5

In [35]:
mat[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [36]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Sumar todos los elementos existentes en mat

In [37]:
mat.sum()

325

In [38]:
np.sum(mat)

325

#### Calcular la desviación estándar del array mat

In [39]:
mat.std()

7.211102550927978

#### Calcular la suma de cada columna en mat

In [40]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

#### Calcular la suma de cada fila en mat

In [41]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])